services:
  db_dev:
    build:
      context: .
      dockerfile: deploy/db/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ./deploy/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  db_testing:
    build:
      context: .
      dockerfile: deploy/db/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./deploy/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
  app_dev:
    build:
      context: .
      dockerfile: deploy/dev/Dockerfile
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - ENV=${ENV}
      - UI_URL=${UI_URL}
    depends_on:
      - db_dev
  test:
    build:
      context: .
      dockerfile: deploy/testing/Dockerfile
    stdin_open: true
    environment:
      - ENV=${ENV}
    tty: true
    command: sh -c "python -B -m pytest -l --color=yes --cov=core_app --cov-config=./tests/.coveragerc --cov-report term --cov-report html:coverage --junit-xml=junit.xml --rootdir=. ./tests"
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - db_testing